server:
  port: 5183
  servlet:
    context-path: /cmfz_cbw
  tomcat:
    uri-encoding: UTF-8
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/cmfz
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB
  redis:
    database: 0
    host: 192.168.18.75
    port: 6666
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.baizhi.entity
logging:
  level:
    root: info
    com.baizhi.dao: debug